# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ad176e538e21e1f78f08654f91a4109dbe6647e82ab928c5380b59b1faed08bb7016561522194a9ae068950305f58227f8ba084ef2881000397a90d1d3cb5d31

test:
  secret_key_base: a243363ea56b2fac7105b8b06e439eb22cbacb29722b89fa25586be1201e0e51d368e49df4d4f77606bef2188f6fc45739ebb9d359ac67766d4e53607e03e4ce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
